config/routes.rb
Rails.application.routes.draw do
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/nest/callback', to: 'nest#create', as: :nest
  get  '/auth/smappee', to: 'smappee#new', as: :new_smappee
  post '/auth/smappee/callback', to: 'smappee#create', as: :smappee
  get '/auth/philips', to: 'philips#new', as: :new_philips
  post '/auth/philips/', to: 'philips#create', as: :philips

  resources :houses, only: [:show, :new, :create, :edit, :update]
  resources :devices do
    resources :types, only: :index
  end
  resources :actions, only: :index
  resources :brands, only: :index
  resources :consumptions , only: :show

  root to: 'pages#home'
end

app/controllers/smappee_controller.rb
class SmappeeController < ApplicationController

  def new
    @model = Credentials.new
  end

  def create
    @model = Credentials.new(credential_params)

    adapter = SmappeeAdapter.new(ENV['SMAPPEE_CLIENT_ID'], ENV['SMAPPEE_CLIENT_SECRET'])

    begin
      device = AddDeviceService.new(adapter).call(@model.username, @model.password, house)
      adapter.device = device

      redirect_to edit_house_path(house)
    rescue RestClient::BadRequest => e
      flash.now[:alert] = "Nous n'avons pas pu ajouter votre objet. Veuillez vérifier vos informations."
      render :new
    end
  end

  private

  def house
    current_user.house
  end

  def credential_params
    params.require(:credentials).permit(:username, :password)
  end

end

app/views/smappee/new.html.erb
<div class="container">
  <h1 class="text-center">Connectez vous à votre compte Smappee</h1>
  <div class="row">
    <div class="col-12 col-sm-6  col-sm-offset-3">
      <%= simple_form_for @model, url: smappee_path do |f|  %>
        <%= f.input :username, required: true, autofocus: true %>
        <%= f.input :password, type: :password, required: true %>
        <div class="form-actions">
          <%= f.button :submit, "Valider" %>
          <%= link_to "Retour", devices_path, class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>