config/routes.rb
Rails.application.routes.draw do
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/nest/callback', to: 'nest#create', as: :nest
  get  '/auth/smappee', to: 'smappee#new', as: :new_smappee
  post '/auth/smappee/callback', to: 'smappee#create', as: :smappee
  get '/auth/philips', to: 'philips#new', as: :new_philips
  post '/auth/philips/', to: 'philips#create', as: :philips

  resources :houses, only: [:show, :new, :create, :edit, :update]
  resources :devices do
    resources :types, only: :index
  end
  resources :actions, only: :index
  resources :brands, only: :index
  resources :consumptions , only: :show

  root to: 'pages#home'
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :type
  belongs_to :house
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]


  def index

    redirect_to edit_house_path(current_user.house.id) unless Device.where(house: current_user.house).count > 0


    @graph_instant_gas = Consumption.where("energy = 'gas'").last(10).map do |c|
      [c.stamp.strftime("%H:%M") , c.value]

    end

    @graph_instant_water = Consumption.where("energy = 'water'").last(10).map do |c|
      [c.stamp.strftime("%H:%M") , c.value]
    end

    @graph_instant_solar = Consumption.where("energy = 'solar'").last(10).map do |c|
      [c.stamp.strftime("%H:%M") , c.value]
    end

    @graph_instant_elec = Consumption.where("energy = 'elec'").last(10).map do |c|
      [c.stamp.strftime("%H:%M") , c.value]
    end

    @device = Device.find_by(name: 'Nest')

    if @device.present?
      headers = {
        authorization: "Bearer #{@device.token}",
        content_type: 'application/json'
      }

      res = RestClient.get("https://developer-api.nest.com/devices/cameras", headers)
      nest = JSON.parse(res.body).first
      @camera_url = nest[1]['web_url']
    end

    # @smappee = Device.find_by_name("Smappee");
    #
    # service = service_location(@smappee.token)
    # consumptions = get_consumption(@smappee.token, service['serviceLocations'][0]['serviceLocationId'])
    # consumptions = consumptions['consumptions']
    # @graph_instant_solar = consumptions.map do |consumption|
    #   timestamp = consumption['timestamp']/1000
    #   date = DateTime.strptime(timestamp.to_s,'%s').strftime("%H:%M")
    #   p "^"*100
    #   p timestamp
    #   p date
    #   [date, consumption['solar']]
    # end
    #
    # @graph_instant_elec = consumptions.map do |consumption|
    #   timestamp = consumption['timestamp']/1000
    #   date = DateTime.strptime(timestamp.to_s,'%s').strftime("%H:%M")
    # [date, consumption['consumption']]
    # end
    #
    # @graph_instant_gas = []
    # Consumption.where("energy = 'gas'").last(10).each do |c|
    #   @graph_instant_gas << [c.stamp.strftime("%H:%M") , c.value]
    # end
    #
    # @graph_instant_water = []
    # Consumption.where("energy = 'water'").last(10).each do |c|
    #   @graph_instant_water << [c.stamp.strftime("%H:%M") , c.value]
    # end
    #
    # #  list only the devices of the house vs current user
    @devices = Device.where(house: current_user.house)
    @light_devices = Device.where(house: current_user.house, type: Type.where(name: 'Lampes').first)
    @thermostat = Device.where(house: current_user.house, type: Type.where(name: 'Thermostat').first).first
    @camera = Device.where(house: current_user.house, type: Type.where(name: 'Camera').first).first
  end

  def show
  end

  def new
    @device = Device.new
  end

  def create

    @device = Device.new(device_params)
    @device[:house_id]= current_user.house.id

    if @device.save
      if @device.type.brand_id == 3
        redirect_to "https://home.nest.com/login/oauth2?client_id=#{ENV['NEST_ID']}&state=STATE&redirect_uri=#{nest_callback_url}"
      else
        redirect_to devices_path
      end
    end
  end

  def edit
  end

  def update
    @device.update(device_params)
    redirect_to devices_path
  end

  def destroy
    @device.destroy
    redirect_to devices_path
  end

  # def nestcallback
  #   @code = params[:code]
  #   require 'rest-client'
  #   payload = {
  #     grant_type: 'authorization_code',
  #     client_id: ENV['NEST_ID'],
  #     client_secret: ENV['NEST_SECRET'],
  #     code: params[:code]
  #   }
  #   headers = { content_type: 'application/x-www-form-urlencoded' }
  #   res = RestClient.post("https://api.home.nest.com/oauth2/access_token", payload, headers)
  #   response = JSON.parse(res.to_s)
  #   response["access_token"]
  #   headers = {
  #     authorization: "Bearer #{response['access_token']}",
  #     content_type: 'application/json'
  #   }
  #
  #   res = RestClient.get("https://developer-api.nest.com/devices/cameras", headers)
  #   p '?' * 200
  #   @devices = JSON.parse(res.to_s)
  # end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name, :type_id, :house_id)
  end

  def service_location(token)
    begin
      headers = {
        content_type: 'application/json',
        authorization: "Bearer #{token}"
      }

      res = RestClient.get("https://app1pub.smappee.net/dev/v1/servicelocation", headers)
      p '!'*100
      JSON.parse(res.to_s)
    rescue => e
        p '!'*100
        p e
    end

  end

  def get_consumption(token, id)
    now = Time.now.to_time.to_i*1000
    headers = {
      content_type: 'application/json',
      authorization: "Bearer #{token}"
    }

    res = RestClient.get("https://app1pub.smappee.net/dev/v1/servicelocation/#{id.to_s}/consumption?aggregation=2&from=1520590013000&to=#{now}", headers)
    JSON.parse(res.to_s)
  end
end

app/views/devices/destroy.html.erb
<h1>Devices#destroy</h1>
<p>Find me in app/views/devices/destroy.html.erb</p>

app/views/devices/edit.html.erb
<div class="container">
  <h1>Mettre à jour objet connecté</h1>
  <div class="row">
    <div class="col-xs-12 col-md-4">

    <h2><%=  "#{@device.type.name} #{@device.type.brand.name}"  %></h2>

      <%= simple_form_for (@device) do |f|  %>
      <%= f.input :name  %>
      <%= f.button :submit, "Enregistrer", class:"btn btn-success" %>
      <%= link_to "Retour", devices_path, class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

<div class="edit">
  <div class="editform">

      <div class="form-inputs">
        <div class="row">
          <div class="col-md-12 ml-auto mr-auto">

            <div class="card card-signup">
              <form class="form" method="" action="">
                <div class="card-header card-header-primary ">
                  <h3>Mes objets</h3>
                </div>
                <div class="card-body">
                  <span class="bmd-form-group">
                    <div class="input-group">
                      <% @devices = current_user.house.devices %>
                      <%= link_to " Ajouter un objet", new_device_path, class: "btn btn-default" %>
                    </div>
                  </span>
                </div>
              </form>
            </div>
            <%= render "shared/actions_objects", device: @devices %>
            <div class="form-actions">
              <!-- <%= link_to "Retour", devices_path, class:"btn btn-success" %> -->
            </div>
          </div>
        </div>
      </div>
      </div>
</div>

app/views/devices/index.html.erb
<% content_for :meta_title, "Energy Saver is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Energy saver saves you tons of money helping you to reduce your consumption" %>
<% content_for :meta_image, image_path('bg.jpg') %>

<div class="container ">
  <h1>Dashboard</h1>
  <div class="row dashboard-card">
    <div class="col-xs-12 col-sm-3 col-md-4">
      <%= render "shared/card_smappee", graph1: @graph_instant_elec, graph2: @graph_instant_solar, name:"Electricité", multiline: true  %>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-4">
      <%= render "shared/card_camera", device: @camera if @camera.present? %>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-4">
      <%= render "shared/card_lights", devices: @light_devices if @light_devices.present? %>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-4">
      <%= render "shared/card_thermostat", device: @thermostat if @thermostat.present? %>
    </div>
  </div>
</div>

app/views/devices/nestcallback.html.erb
<div class="container">
  <div class="row">
    <% @devices.each do |key, value| %>
      <div class="col-xs-12 col-md-4">
        <div class="card card-nav-tabs light">
          <div class="card-header card-header-primary">
            <h3><%= value['web_url']%></h3>
          </div>
          <div class="card-body">
            <%= link_to 'Regarder', actions_path, class:'btn btn-primary smappee', type:"button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/devices/new.html.erb
<div class="container">
  <h1>Ajouter un objet connecté</h1>
  <%= simple_form_for (@device) do |f|  %>
  <%= f.input :name, required: true, autofocus: true  %>
  <%= f.input :id, label: "Brand:", required: true, collection: Brand.all.collect {|b| [ b.name, b.id ] } %>
  <%= f.input :type_id, label: "type", required: true, collection: Type.all.collect {|t| [ t.name, t.id ] } %>


    <div class="form-actions">
      <%= f.button :submit, "Valider" %>
      <%= link_to "Retour", devices_path, class:"btn btn-success" %>
    </div>

  <% end %>


  <div class="container">
    <%= link_to 'Connecter ma caméra Nest', "https://home.nest.com/login/oauth2?client_id=#{ENV['NEST_ID']}&state=STATE&redirect_uri=#{nest_callback_url}" %>
  </div>
  <%= link_to 'connect hue', "https://api.meethue.com/oauth2/auth?appid=#{ENV['HUE_CLIENT_ID']}&clientid=71465&deviceid=#{244}&devicename=energy-saver&state=gakbjgmbjkgkmqdjbgkmqb&response_type=code"%>
</div>

app/views/devices/show.html.erb
<div class="container">
  <h1>Mettre à jour objet connecté</h1>
  <div class="row">
    <div class="col-xs-12 col-md-4">

    <h2><%=  "Type: #{@device.type.name}" %><h2>
    <h2><%=  "Brand: #{@device.type.brand.name}"%></h2>
    <h2><%= "Name: #{@device.name} "  %></h2>


      <%= link_to "Retour", devices_path, class:"btn btn-success" %>
    </div>
  </div>
</div>

app/views/devices/update.html.erb
<h1>Devices#update</h1>
<p>Find me in app/views/devices/update.html.erb</p>