config/routes.rb
Rails.application.routes.draw do
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/nest/callback', to: 'nest#create', as: :nest
  get  '/auth/smappee', to: 'smappee#new', as: :new_smappee
  post '/auth/smappee/callback', to: 'smappee#create', as: :smappee
  get '/auth/philips', to: 'philips#new', as: :new_philips
  post '/auth/philips/', to: 'philips#create', as: :philips

  resources :houses, only: [:show, :new, :create, :edit, :update]
  resources :devices do
    resources :types, only: :index
  end
  resources :actions, only: :index
  resources :brands, only: :index
  resources :consumptions , only: :show

  root to: 'pages#home'
end

app/views/shared/_actions_objects.html.erb
<div class="container">
  <div class="row">
      <% @devices.each do |device| %>
      <div class="col-xs-12 col-sm-3 col-md-4">
      <div class="card card-nav-tabs">
        <div class="card-header card-header-primary">
          <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <ul class="nav nav-tabs" data-tabs="tabs">
                <li class="nav-item">
                  <h4><%= device.name %></h4>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card-body card-product">
          <div class="tab-content ">
            <div class="tab-pane active" >
              <% provider = PROVIDERS.find { |provider| device.type.name == provider[:type] }%>
              <%= provider[:name] %>
              <%= image_tag "providers/#{provider[:image]}", class: 'img-circle img-thumbnail' %>
              <%= link_to "Supprimer", device_path(device.id) , method: "delete", class: "btn btn-default " %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class="card card-nav-tabs">
        <div class="card-header card-header-primary">
          <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <ul class="nav nav-tabs" data-tabs="tabs">
                <li class="nav-item">
                  <a class="nav-link active" href="#home" data-toggle="tab">Consommation</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#updates" data-toggle="tab">Production</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card-body ">
          <div class="tab-content text-center">
            <div class="tab-pane active" id="profile">
              <p>
                Du graphique ou du texte
                <br>
                Quidem iis deterritum enim eruditi quidem est est aut fuisset te eruditi ita ne artibus quamquam artibus qui alios ipse deterruisset te tibi est quidem alios videri te tenent necesse.
              </p>
            </div>
            <div class="tab-pane" id="messages">
              <p>
                Du graphique ou du texte
              </p>
            </div>
            <div class="tab-pane" id="settings">
              <p>
                Du graphique ou du texte
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_card_camera.html.erb
<!-- <%= link_to device_path(device) do %>
  <div class="card card-nav-tabs light">
    <div class="card-header card-header-primary">
      <h3><%= device.name %></h3>
    </div>
    <div class="card-body">
      <%= link_to 'Regarder', actions_path, class:'btn btn-primary smappee', type:"button" %>
    </div>
  </div>
<% end %> -->

<div class="card">
  <div class="card-header card-header-primary">
    <h3><%= device.name %></h3>
  </div>
  <div class="body-bottom">
    <div class="card-body  light align">
      <%= link_to 'Regarder', @camera_url, class:'btn btn-primary smappee', type:"button", target: '_blank' %>
    </div>
  </div>
</div>

app/views/shared/_card_lights.html.erb
<div class="card">
  <div class="card-header card-header-primary">
    <h3><%= "Lumière" %></h3>
  </div>
  <div class="body-bottom">
    <!-- <div class="">
      <h4 id="brand-title">Smappee</h4>
    </div> -->
    <div class="card-body  light align">
      <% @light_devices.each do |device| %>
      <%= link_to "#" do %>
      <div class="">
        <%= device.name %>
      </div>
      <button id="<%= device.name.delete(' ') %>" type="button" class="btn btn-primary btn-round"></button>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_card_smappee.html.erb
<div class="card">
  <div class="card-header card-header-primary">
    <h3><%= name %></h3>
  </div>
  <div class="body-bottom">
    <div class="card-body">
      <div class="chart smappee">
        <% if multiline %>
        <%= line_chart [
          {name: "Electricité", data: graph1 },
          {name: "Solaire", data: graph2}
          ], defer: true, class: "chartsize", height: "150px", width: "210px", points: false %>
          <% else %>
          <%= line_chart graph, defer: true, class: "chartsize", height: "150px", width: "210px", points: false %>
          <% end %>
        </div>
      </div>
      <div class="bottom-chart">
        <%= link_to "Voir en détail", consumption_path(id: 'consumption_path(day)'), type:"button", class:"btn btn-primary" %>
      </div>
  </div>
</div>

app/views/shared/_card_thermostat.html.erb
<div class="card card-nav-tabs light">
  <div class="card-header card-header-primary">
    <h3><%= device.name %></h3>
  </div>
  <div class="card-body">
    <!-- thermostat  -->

    <%= render "shared/modal_thermostat", device: @thermostat  %>

<!-- thermostat -->
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer ">
  <div class="footer-links">
  
  </div>
</div>

app/views/shared/_modal_nest.erb
<!-- thermostat sart   ... -->

<script>
  var ambient_temp = <%= @ambient_temp %>;
  var set_temp = <%= @set_temp %>;
</script>

<div id='container'>

  <div id='thermostat'></div>



  <label><span></span>
    <div id='input_ambient_temperature'> </div>
  </label>

  <label><span></span>
    <div id='input_target_temperature'></div>
  </label>
</div>

<label><span>Absent</span>
  <select id='input_away'>
    <option value=''>Non</option>
    <option value='1'>Oui</option>
  </select>
</label>

<label><span></span>
  <div id='input_state'>
  </div>
</label>

<label><span></span>
  <div id='input_leaf'>
  </div>
</label>

<!-- thermostat end -->

app/views/shared/_modal_thermostat.erb
<!-- Large modal -->

<% @set_temp = 21  %>
<% @ambient_temp = 18  %>

<button type="button" class="btn btn-therm" data-toggle="modal" data-target=".bd-example-modal-lg"><%= "#{@ambient_temp}  °C"%></button>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <%= render "shared/modal_nest", device: @thermostat  %>

    </div>
  </div>
  <div >

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-shadow">
    <!-- Logo -->
    <a href="/devices" class="navbar-wagon-brand">
      <div class="global-brand">
        <h4>ENERGY SAVER</h4>
      </div>
    </a>


    <!-- Links when logged in -->
    <% if user_signed_in? %>


      <!-- Right Navigation -->
      <div class="navbar-wagon-right">
        <a href="" class="navbar-wagon-item navbar-wagon-link hidden-xs"><%= current_user.house.name%></a>



        <!-- Profile picture with dropdown list -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <% @avatar = current_user.facebook_picture_url || "https://s3-eu-west-1.amazonaws.com/vegebase/fallback/avatar_default.png" %>
            <% @avatar = User.find(current_user.id).photo unless User.find(current_user.id)[:photo] == nil %>
            <%= image_tag @avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to "Mon profil", edit_user_registration_path %></li>
              <li><%= link_to "Mes objets",edit_house_path(current_user.house.id) %></li>
              <li><%= link_to "Statistiques", consumption_path('consumption_path(day)') %></li>
              <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Dropdown appearing on mobile only -->
      <%#= render 'shared/navbar_phone' %>

    <% else %>
      <!-- Login link (when logged out) -->
      <!-- <% @avatar = "https://s3-eu-west-1.amazonaws.com/vegebase/fallback/avatar_default.png" %>
      <%= link_to "Connexion", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %> -->

      <!-- Dropdown appearing on mobile only -->
      <%#= render 'shared/navbar_phone' %>
    <% end %>
</div>

app/views/shared/_navbar_phone.html.erb
<!-- Dropdown appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="#">Host</a></li>
      <li><a href="#">Trips</a></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar_transparent.html.erb
  <div class="">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <div class="global-brand">
        <h4>ENERGY SAVER</h4>
      </div>
    </a>
  </div>

app/views/shared/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/assets/stylesheets/config/material-kit.scss">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="main">
       <%= render 'shared/navbar' %>
       <%= render 'shared/flashes' %>
       <div class="main-content">
         <div class="content">
           <%= yield %>
         </div>
         <%= render 'shared/footer' %>
       </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="/assets/js/core/jquery.min.js"></script>
    <script src="/assets/js/core/popper.min.js"></script>
    <script src="/assets/js/bootstrap-material-design.js"></script>
    <script src="/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
    <script src="/assets/js/plugins/nouislider.min.js"></script>
    <script src="/assets/js/material-kit.js?v=2.0.0"></script>
  </body>
</html>