config/routes.rb
Rails.application.routes.draw do
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin } do
  mount Sidekiq::Web => '/sidekiq'
  # end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/nest/callback', to: 'nest#create', as: :nest
  get  '/auth/smappee', to: 'smappee#new', as: :new_smappee
  post '/auth/smappee/callback', to: 'smappee#create', as: :smappee
  get '/auth/philips', to: 'philips#new', as: :new_philips
  post '/auth/philips/', to: 'philips#create', as: :philips

  resources :houses, only: [:show, :new, :create, :edit, :update]
  resources :devices do
    resources :types, only: :index
  end
  resources :actions, only: :index
  resources :brands, only: :index
  resources :consumptions , only: :show

  root to: 'pages#home'
end

app/controllers/philips_controller.rb
class PhilipsController < ApplicationController

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)
    @device[:house_id]= current_user.house.id
    @device[:type_id]= Type.find_by(name: 'Lampes').id
    if @device.save
      redirect_to edit_house_path(current_user.house)
    end
  end

  private

  def device_params
    params.require(:device).permit(:name, :type_id, :house_id)
  end
end

app/views/philips/new.html.erb
<div class="container">
  <h1>Ajouter une Lampe Philips Hue</h1>
  <%= simple_form_for(@device, :url => new_philips_path) do |f|  %>
  <%= f.input :name, required: true, autofocus: true  %>

    <div class="form-actions">
      <%= f.button :submit, "Valider" %>
      <%= link_to "Retour", devices_path, class:"btn btn-success" %>

    </div>

  <% end %>

</div>